databases:
  - name: helpjuice-search-box
    databaseName: helpjuice_search_box_production
    user: helpjuice_search_box
    plan: free

services:
  - type: web
    name: helpjuice-search-box
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helpjuice-search-box
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default